---
- name: add fwpp repo
  ansible.builtin.yum_repository:
    name: fwpp
    description: Firmware Pack for ProLiant
    baseurl: "{{ repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ repo_gpg_key }}"
  tags: repo

- name: install packages
  ansible.builtin.package:
    name: "{{ pkg }}"
    state: present
  loop: "{{ hpe_fwpp_packages }}"
  loop_control:
    loop_var: pkg
  when: hpe_fwpp_packages is defined
  tags: packages
