---
- name: add HPE-spp repo
  ansible.builtin.yum_repository:
    name: HPE-spp
    description: HPE Software Delivery Repository for spp
    baseurl: "{{ repo_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ repo_gpg_key }}"
  tags: repo

- name: install packages
  ansible.builtin.package:
    name: "{{ pkg }}"
    state: present
  loop: "{{ hpe_spp_packages }}"
  loop_control:
    loop_var: pkg
  when: hpe_spp_packages is defined
  tags: packages
